import { LocalSound } from "../types";

export const localSounds: LocalSound[] = [
  // Add more tracks as needed
  {
    id: "scouting4u-1",
    title: "Beat Butcha",
    artist: "Scouting4U",
    duration: 240,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Beat Butcha - Big Score (90 BPM) - Trap.mp3",
  },
  {
    id: "scouting4u-2",
    title: "Big Score",
    artist: "Scouting4U",
    duration: 128,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Beat Butcha - Big Score (90 BPM) - Trap (1).mp3",
  },
  {
    id: "scouting4u-3",
    title: "Highlight Reel",
    artist: "Scouting4U",
    duration: 151,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Highlight Reel.mp3",
  },
  {
    id: "scouting4u-4",
    title: "Highlight",
    artist: "Scouting4U",
    duration: 177,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Highscore (1).mp3",
  },
  {
    id: "scouting4u-5",
    title: "Hot Line",
    artist: "Scouting4U",
    duration: 240,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Hot Line.mp3",
  },
  {
    id: "scouting4u-6",
    title: "Another Hot Line",
    artist: "Scouting4U",
    duration: 126,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Hot Line (1).mp3",
  },
  {
    id: "scouting4u-7",
    title: "In the Air Tonight",
    artist: "Scouting4U",
    duration: 240,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/In the Air Tonight.mp3",
  },
  {
    id: "scouting4u-8",
    title: "In the Air",
    artist: "Scouting4U",
    duration: 158,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/In the Air Tonight (1).mp3",
  },
  {
    id: "scouting4u-9",
    title: "Jump Shot",
    artist: "Scouting4U",
    duration: 240,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Jump Shot.mp3",
  },
  {
    id: "scouting4u-10",
    title: "Shooting",
    artist: "Scouting4U",
    duration: 112,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Jump Shot (1).mp3",
  },
  {
    id: "scouting4u-11",
    title: "Kronos",
    artist: "Scouting4U",
    duration: 138,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Kronos.mp3",
  },
  {
    id: "scouting4u-12",
    title: "Kronos Forever",
    artist: "Scouting4U",
    duration: 238,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Kronos (1).mp3",
  },
  {
    id: "scouting4u-13",
    title: "Last One Standing",
    artist: "Scouting4U",
    duration: 240,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Last One Standing.mp3",
  },
  {
    id: "scouting4u-14",
    title: "Standing Alone",
    artist: "Scouting4U",
    duration: 237,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Last One Standing (1).mp3",
  },
  {
    id: "scouting4u-15",
    title: "Look at Me Now",
    artist: "Scouting4U",
    duration: 202,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Look at Me Now.mp3",
  },
  {
    id: "scouting4u-16",
    title: "Look at Me",
    artist: "Scouting4U",
    duration: 90,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Look at Me Now (1).mp3",
  },
  {
    id: "scouting4u-17",
    title: "No Me Conoces",
    artist: "Scouting4U",
    duration: 208,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/No Me Conoces.mp3",
  },
  {
    id: "scouting4u-18",
    title: "That's The Way",
    artist: "Scouting4U",
    duration: 139,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/That's The Way.mp3",
  },
  {
    id: "scouting4u-19",
    title: "That's The Way We Do It",
    artist: "Scouting4U",
    duration: 99,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/That's The Way (1).mp3",
  },
  {
    id: "scouting4u-20",
    title: "Empty The Tank",
    artist: "Scouting4U",
    duration: 209,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Empty The Tank.mp3",
  },
  {
    id: "scouting4u-21",
    title: "All In",
    artist: "Scouting4U",
    duration: 232,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/All In.mp3",
  },
  {
    id: "scouting4u-22",
    title: "The Best",
    artist: "Scouting4U",
    duration: 240,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/The Best (2).mp3",
  },
  {
    id: "scouting4u-23",
    title: "Live My Life",
    artist: "Scouting4U",
    duration: 240,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Live My Life (2).mp3",
  },
  {
    id: "scouting4u-24",
    title: "My Life",
    artist: "Scouting4U",
    duration: 127,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Live My Life (1).mp3",
  },
  {
    id: "scouting4u-25",
    title: "Meijin",
    artist: "Scouting4U",
    duration: 123,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Meijin.mp3",
  },
  {
    id: "scouting4u-26",
    title: "Kaizen",
    artist: "Scouting4U",
    duration: 227,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Meijin (1).mp3",
  },
  {
    id: "scouting4u-27",
    title: "The best you can",
    artist: "Scouting4U",
    duration: 133,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/The best you can.mp3",
  },
  {
    id: "scouting4u-28",
    title: "The best",
    artist: "Scouting4U",
    duration: 240,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/The best you can (1).mp3",
  },
  {
    id: "scouting4u-29",
    title: "All Out",
    artist: "Scouting4U",
    duration: 159,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Empty the tank.mp3",
  },
  {
    id: "scouting4u-30",
    title: "Nothing Left",
    artist: "Scouting4U",
    duration: 91,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Empty the tank (1).mp3",
  },
  {
    id: "scouting4u-31",
    title: "Now and Always",
    artist: "Scouting4U",
    duration: 240,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Now or never.mp3",
  },
  {
    id: "scouting4u-32",
    title: "Never",
    artist: "Scouting4U",
    duration: 240,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/Now or never (1).mp3",
  }/*,
  {
    id: "scouting4u-33",
    title: "",
    artist: "Scouting4U",
    duration: ,
    file: "https://remotionlambda-euwest1-oqzlxtyguv.s3.eu-west-1.amazonaws.com/sound/",
  },*/
];
